- name: Install and start nginx
  apt:
   name: nginx
   state: present
  notify:
   - Restart Nginx

- name: Configure Nginx
  template:
   src: nginx.conf
   dest: /etc/nginx/nginx.conf
  notify:
   - Restart Nginx
